import { NextResponse } from "next/server";

export async function GET() {
    return NextResponse.json({
        approved: [
            {
                id: "1",
                name: "기초부터 시작",
                variant: "memberOpen",
                title: "토익 스터디 1",
                startDate: "2025-09-01",
                endDate:   "2025-11-30",
                time: "월, 수 19:00",
                currentMembers: 3,
                maxMembers: 8,
                tag: "외국어",
            },
            {
                id: "2",
                name: "실전 대비반",
                variant: "memberOpen",
                title: "토익 스터디 2",
                startDate: "2025-09-05",
                endDate:   "2025-12-10",
                time: "화, 목 20:00",
                currentMembers: 5,
                maxMembers: 8,
                tag: "토익",
            },
            {
                id: "3",
                name: "주말 집중반",
                variant: "memberOpen",
                title: "토익 스터디 3",
                startDate: "2025-09-10",
                endDate:   "2025-12-20",
                time: "토 14:00",
                currentMembers: 2,
                maxMembers: 6,
                tag: "영어",
            },
        ],
        pending: [
            {
                id: "1",
                name: "기출 문제 풀이",
                variant: "memberClosed",
                title: "CS 면접 스터디 1",
                startDate: "2025-09-12",
                endDate:   "2025-11-01",
                time: "화, 목 21:00",
                currentMembers: 4,
                maxMembers: 8,
                tag: "면접",
            },
            {
                id: "2",
                name: "코딩테스트 대비",
                variant: "memberClosed",
                title: "알고리즘 스터디 1",
                startDate: "2025-09-15",
                endDate:   "2025-11-30",
                time: "수 20:00",
                currentMembers: 6,
                maxMembers: 10,
                tag: "알고리즘",
            },
            {
                id: "3",
                name: "자료구조 심화",
                variant: "memberClosed",
                title: "자료구조 스터디 1",
                startDate: "2025-09-20",
                endDate:   "2025-12-05",
                time: "월 19:30",
                currentMembers: 3,
                maxMembers: 7,
                tag: "CS",
            },
        ],
        rejected: [
            {
                id: "1",
                name: "회화 중심",
                variant: "memberClosed",
                title: "영작 스터디 1",
                startDate: "2025-09-18",
                endDate:   "2025-11-25",
                time: "금 21:00",
                currentMembers: 4,
                maxMembers: 6,
                tag: "영어",
            },
            {
                id: "2",
                name: "단기 집중반",
                variant: "memberClosed",
                title: "코테 준비 1",
                startDate: "2025-09-22",
                endDate:   "2025-12-01",
                time: "토 10:00",
                currentMembers: 2,
                maxMembers: 5,
                tag: "코딩테스트",
            },
            {
                id: "3",
                name: "ES6 마스터",
                variant: "memberClosed",
                title: "JS 심화 1",
                startDate: "2025-09-25",
                endDate:   "2025-12-15",
                time: "수 19:00",
                currentMembers: 5,
                maxMembers: 9,
                tag: "코딩",
            },
        ],
        recruiting: [
            {
                id: "1",
                name: "핵심 개념 정리",
                variant: "leaderOpen",
                title: "JS 심화 1",
                startDate: "2025-09-25",
                endDate:   "2025-12-15",
                time: "수 19:00",
                currentMembers: 5,
                maxMembers: 9,
                tag: "JS",
            },
            {
                id: "2",
                name: "프로젝트 실습",
                variant: "leaderOpen",
                title: "JS 심화 2",
                startDate: "2025-09-28",
                endDate:   "2025-12-20",
                time: "일 20:00",
                currentMembers: 4,
                maxMembers: 8,
                tag: "JS",
            },
            {
                id: "3",
                name: "알고리즘 응용",
                variant: "leaderOpen",
                title: "JS 심화 3",
                startDate: "2025-10-02",
                endDate:   "2025-12-22",
                time: "목 21:00",
                currentMembers: 6,
                maxMembers: 10,
                tag: "JS",
            },
        ],
        completed : [
            {
                id: "1",
                name: "핵심 개념 정리",
                variant: "leaderClosed",
                title: "JS 심화 1 (마감)",
                startDate: "2025-09-25",
                endDate:   "2025-12-15",
                time: "수 19:00",
                currentMembers: 9,
                maxMembers: 9,
                tag: "JS",
            },
            {
                id: "2",
                name: "프로젝트 실습",
                variant: "leaderClosed",
                title: "JS 심화 2 (마감)",
                startDate: "2025-09-28",
                endDate:   "2025-12-20",
                time: "일 20:00",
                currentMembers: 8,
                maxMembers: 8,
                tag: "JS",
            },
            {
                id: "3",
                name: "알고리즘 응용",
                variant: "leaderClosed",
                title: "JS 심화 3 (마감)",
                startDate: "2025-10-02",
                endDate:   "2025-12-22",
                time: "목 21:00",
                currentMembers: 10,
                maxMembers: 10,
                tag: "JS",
            },
        ]
    });
}
